/**
 * @fileoverview Products Redux Slice - State management for product operations
 * 
 * This file contains the Redux Toolkit slice for managing product state,
 * including async thunks for API operations and reducers for state updates.
 * Handles loading states, error management, and CRUD operations.
 * 
 * @author Demo Copilot Agent Team
 * @version 1.0.0
 */

import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import type { CreateProductData, UpdateProductData, ProductsState } from '../types';
import { productService } from '../services/productService';

/**
 * Async thunk to fetch all products from the API
 * 
 * @returns Promise resolving to array of products
 * @throws Rejects with error message if API call fails
 */
export const fetchProducts = createAsyncThunk(
  'products/fetchProducts',
  async (_, { rejectWithValue }) => {
    try {
      const response = await productService.getAllProducts();
      return response.data;
    } catch (error) {
      return rejectWithValue(error instanceof Error ? error.message : 'Failed to fetch products');
    }
  }
);

/**
 * Async thunk to fetch a single product by ID
 * 
 * @param id - The unique product identifier
 * @returns Promise resolving to the requested product
 * @throws Rejects with error message if product not found or API call fails
 */
export const fetchProductById = createAsyncThunk(
  'products/fetchProductById',
  async (id: string, { rejectWithValue }) => {
    try {
      const response = await productService.getProductById(id);
      return response.data;
    } catch (error) {
      return rejectWithValue(error instanceof Error ? error.message : 'Failed to fetch product');
    }
  }
);

/**
 * Async thunk to create a new product
 * 
 * @param productData - Product creation data without ID (generated by service)
 * @returns Promise resolving to the created product with generated ID
 * @throws Rejects with error message if validation fails or API call fails
 */
export const createProduct = createAsyncThunk(
  'products/createProduct',
  async (productData: CreateProductData, { rejectWithValue }) => {
    try {
      const response = await productService.createProduct(productData);
      return response.data;
    } catch (error) {
      return rejectWithValue(error instanceof Error ? error.message : 'Failed to create product');
    }
  }
);

/**
 * Async thunk to update an existing product
 * 
 * @param productData - Product update data including ID and fields to update
 * @returns Promise resolving to the updated product
 * @throws Rejects with error message if product not found or API call fails
 */
export const updateProduct = createAsyncThunk(
  'products/updateProduct',
  async (productData: UpdateProductData, { rejectWithValue }) => {
    try {
      const response = await productService.updateProduct(productData);
      return response.data;
    } catch (error) {
      return rejectWithValue(error instanceof Error ? error.message : 'Failed to update product');
    }
  }
);

/**
 * Async thunk to delete a product
 * 
 * @param id - The unique identifier of the product to delete
 * @returns Promise resolving to the deleted product's ID
 * @throws Rejects with error message if product not found or API call fails
 */
export const deleteProduct = createAsyncThunk(
  'products/deleteProduct',
  async (id: string, { rejectWithValue }) => {
    try {
      await productService.deleteProduct(id);
      return id;
    } catch (error) {
      return rejectWithValue(error instanceof Error ? error.message : 'Failed to delete product');
    }
  }
);

/**
 * Initial state for the products slice
 * Defines the default state structure for product management
 */
const initialState: ProductsState = {
  products: [],
  loading: false,
  error: null,
  selectedProduct: null,
};

/**
 * Products Redux Slice
 * 
 * Manages all product-related state including:
 * - Product list and selected product
 * - Loading states for async operations
 * - Error handling and messages
 * - CRUD operation state updates
 */
const productsSlice = createSlice({
  name: 'products',
  initialState,
  reducers: {
    /** Clears any existing error message from the state */
    clearError: (state) => {
      state.error = null;
    },
    /** Clears the currently selected product from the state */
    clearSelectedProduct: (state) => {
      state.selectedProduct = null;
    },
  },
  extraReducers: (builder) => {
    builder
      // Fetch products
      .addCase(fetchProducts.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchProducts.fulfilled, (state, action) => {
        state.loading = false;
        state.products = action.payload;
      })
      .addCase(fetchProducts.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload as string;
      })
      // Fetch product by ID
      .addCase(fetchProductById.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchProductById.fulfilled, (state, action) => {
        state.loading = false;
        state.selectedProduct = action.payload;
      })
      .addCase(fetchProductById.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload as string;
      })
      // Create product
      .addCase(createProduct.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(createProduct.fulfilled, (state, action) => {
        state.loading = false;
        state.products.push(action.payload);
      })
      .addCase(createProduct.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload as string;
      })
      // Update product
      .addCase(updateProduct.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(updateProduct.fulfilled, (state, action) => {
        state.loading = false;
        const index = state.products.findIndex(p => p.id === action.payload.id);
        if (index !== -1) {
          state.products[index] = action.payload;
        }
        if (state.selectedProduct?.id === action.payload.id) {
          state.selectedProduct = action.payload;
        }
      })
      .addCase(updateProduct.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload as string;
      })
      // Delete product
      .addCase(deleteProduct.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(deleteProduct.fulfilled, (state, action) => {
        state.loading = false;
        state.products = state.products.filter(p => p.id !== action.payload);
        if (state.selectedProduct?.id === action.payload) {
          state.selectedProduct = null;
        }
      })
      .addCase(deleteProduct.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload as string;
      });
  },
});

export const { clearError, clearSelectedProduct } = productsSlice.actions;
export default productsSlice.reducer;